"""Build a metadata cache from the backed-up solutions and render STATS.md.

Separation of concerns: fetch_submissions.py owns *syncing code*; this script
owns *reporting*. It scans submissions/, fills in any missing problem metadata
(difficulty / topics) from LeetCode, caches it in data/problems.json, and
renders a stats dashboard grouped by difficulty and topic.
"""
import json
import os
import subprocess
import time
from collections import Counter
from datetime import datetime, timezone

from leetcode_api import graphql_post, make_session, slug_of

SUBMISSIONS_DIR = "submissions"
CACHE_PATH = os.path.join("data", "problems.json")
STATS_PATH = "STATS.md"

DIFFICULTY_ORDER = ["Easy", "Medium", "Hard"]

QUESTION_QUERY = """
query getQuestion($titleSlug: String!) {
  question(titleSlug: $titleSlug) {
    questionFrontendId
    title
    difficulty
    topicTags {
      name
    }
  }
}
"""


def load_cache():
    if os.path.exists(CACHE_PATH):
        with open(CACHE_PATH, encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_cache(cache):
    os.makedirs(os.path.dirname(CACHE_PATH), exist_ok=True)
    with open(CACHE_PATH, "w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write("\n")


def solved_timestamp(file_name):
    """Solve date = the (backdated) commit date of the file, else its mtime."""
    path = os.path.join(SUBMISSIONS_DIR, file_name)
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ct", "--", path],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        if out:
            return int(out)
    except Exception:
        pass
    return int(os.path.getmtime(path))


def fetch_question(session_obj, slug):
    _, data = graphql_post(session_obj, QUESTION_QUERY, {"titleSlug": slug})
    if data is None:
        return None
    return (data or {}).get("data", {}).get("question")


def build_cache(session_obj):
    """Ensure every solution file has an entry in the metadata cache."""
    cache = load_cache()
    files = [
        f
        for f in os.listdir(SUBMISSIONS_DIR)
        if os.path.isfile(os.path.join(SUBMISSIONS_DIR, f))
    ] if os.path.isdir(SUBMISSIONS_DIR) else []

    present_slugs = set()
    for file_name in sorted(files):
        slug = slug_of(file_name)
        present_slugs.add(slug)
        qid = file_name.split("-", 1)[0]
        ext = file_name.rsplit(".", 1)[-1]

        entry = cache.get(slug, {})
        # Fetch metadata only if we don't already have the difficulty.
        if not entry.get("difficulty"):
            q = fetch_question(session_obj, slug)
            time.sleep(1)
            if q:
                entry["title"] = q.get("title", slug)
                entry["difficulty"] = q.get("difficulty", "Unknown")
                entry["topics"] = [t["name"] for t in (q.get("topicTags") or [])]
                qid = q.get("questionFrontendId", qid)
                print(f"  fetched metadata for {slug} ({entry['difficulty']})")
            else:
                entry.setdefault("title", slug)
                entry.setdefault("difficulty", "Unknown")
                entry.setdefault("topics", [])

        entry["qid"] = qid
        entry["ext"] = ext
        entry["file"] = file_name
        entry["timestamp"] = solved_timestamp(file_name)
        cache[slug] = entry

    # Drop entries whose file no longer exists.
    for slug in list(cache):
        if slug not in present_slugs:
            del cache[slug]

    return cache


def _bar(count, total, width=20):
    if total == 0:
        return ""
    filled = round(width * count / total)
    return "█" * filled + "░" * (width - filled)


def render_stats(cache):
    """Pure function: turn the metadata cache into STATS.md markdown."""
    problems = sorted(cache.values(), key=lambda p: int(p.get("qid") or 0) or 0)
    total = len(problems)

    diff_counts = Counter(p.get("difficulty", "Unknown") for p in problems)
    lang_counts = Counter(p.get("ext", "?") for p in problems)
    topic_counts = Counter(
        topic for p in problems for topic in p.get("topics", [])
    )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = []
    lines.append("# 📊 LeetCode Stats")
    lines.append("")
    lines.append(f"_Auto-generated by `generate_stats.py` — last updated {now}._")
    lines.append("")
    lines.append(f"**Total solved: {total}**")
    lines.append("")

    # By difficulty
    lines.append("## By difficulty")
    lines.append("")
    lines.append("| Difficulty | Solved | |")
    lines.append("| --- | ---: | --- |")
    for diff in DIFFICULTY_ORDER + [
        d for d in diff_counts if d not in DIFFICULTY_ORDER
    ]:
        if diff in diff_counts:
            c = diff_counts[diff]
            lines.append(f"| {diff} | {c} | `{_bar(c, total)}` |")
    lines.append("")

    # By language
    lines.append("## By language")
    lines.append("")
    lines.append("| Language (ext) | Solved |")
    lines.append("| --- | ---: |")
    for ext, c in lang_counts.most_common():
        lines.append(f"| `{ext}` | {c} |")
    lines.append("")

    # Top topics
    lines.append("## Top topics")
    lines.append("")
    lines.append("| Topic | Solved |")
    lines.append("| --- | ---: |")
    for topic, c in topic_counts.most_common(15):
        lines.append(f"| {topic} | {c} |")
    lines.append("")

    # Full list grouped by difficulty
    lines.append("## Solved problems")
    lines.append("")
    for diff in DIFFICULTY_ORDER + [
        d for d in diff_counts if d not in DIFFICULTY_ORDER
    ]:
        group = [p for p in problems if p.get("difficulty") == diff]
        if not group:
            continue
        lines.append(f"### {diff} ({len(group)})")
        lines.append("")
        lines.append("| # | Problem | Topics | Lang | Solved |")
        lines.append("| ---: | --- | --- | --- | --- |")
        for p in group:
            date = datetime.fromtimestamp(
                int(p.get("timestamp", 0)), timezone.utc
            ).strftime("%Y-%m-%d")
            link = f"[{p.get('title', p['file'])}]({SUBMISSIONS_DIR}/{p['file']})"
            topics = ", ".join(p.get("topics", [])[:4])
            lines.append(
                f"| {p.get('qid', '')} | {link} | {topics} | `{p.get('ext', '')}` | {date} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main():
    session_obj = make_session()
    cache = build_cache(session_obj)
    save_cache(cache)
    with open(STATS_PATH, "w", encoding="utf-8") as f:
        f.write(render_stats(cache))
    print(f"Wrote {STATS_PATH} ({len(cache)} problems) and {CACHE_PATH}.")


if __name__ == "__main__":
    main()
